name: HeldPermissions
main: me.heldplayer.permissions.Permissions
version: 1.4.0
author: heldplayer
description: Permissions plugin to replace PermissionsBUkkit
commands:
  permissions:
    description: Main plugin command
    usage: |
        /<command> reload - reload the configuration from disk.
        /<command> check <node> [player] - check if a player or the sender has a permission (any plugin).
        /<command> info <node> - prints information on a specific permission.
        /<command> group - list group-related commands.
        /<command> group list - list all groups.
        /<command> group players <group> - list players in a group.
        /<command> group setperm <group> <[world:]node> [true|false] - set a permission on a group.
        /<command> group unsetperm <group> <[world:]node> - unset a permission on a group.
        /<command> player - list player-related commands.
        /<command> player groups <player> - list groups a player is in.
        /<command> player setgroup <player> <group,...> - set a player to be in only the given groups.
        /<command> player addgroup <player> <group> - add a player to a group.
        /<command> player removegroup <player> <group> - remove a player from a group.
        /<command> player setperm <player> <[world:]node> [true|false] - set a permission on a player.
        /<command> player unsetperm <player> <[world:]node> - unset a permission on a player.
#        /<command> dump [player] [page] - prints info about a player's (or the sender's) permissions.
    aliases: [perms]
    permission: permissions.command
  rank:
    description: Command to rank people
    usage: /<command> [player] [rank1] [rank2] ...
    permission: permissions.rank
  promote:
    description: Command to promote people, but not demote them
    usage: /<command> [player] [rank]
    permission: permissions.promote
  perm:
    description: Debug command
    usage: Invalid usage
permissions:
  permissions.*:
    children:
      permissions.build: true
      permissions.command: true
      permissions.rank: true
    default: op
    description: Gives full access to HeldPermissions
  permissions.build:
    description: Allows players to build
  permissions.rank:
    description: Allows players to use the /rank command
  permissions.command:
    description: Allows players to use the /permissions command
  permissions.command.*:
    description: Allows players to use all /permissions subcommands