name: HeldPermissions
main: me.heldplayer.permissions.Permissions
version: 1.4.0
author: heldplayer
description: Permissions plugin to replace PermissionsBUkkit
commands:
  permissions:
    description: Main plugin command
    usage: /<command> help
    aliases: [perms]
    permission: permissions.command
  rank:
    description: Command to rank people
    usage: /<command> [player] [rank1] [rank2] ...
    permission: permissions.rank
  promote:
    description: Command to promote people, but not demote them
    usage: /<command> [player] [rank]
    permission: permissions.promote
  perm:
    description: Debug command
    usage: Invalid usage
permissions:
  permissions.*:
    children:
      permissions.build: true
      permissions.command.*: true
      permissions.rank: true
    default: op
    description: Gives full access to HeldPermissions
  permissions.build:
    description: Allows players to build
  permissions.rank:
    description: Allows players to use the /rank command
  permissions.command.*:
    description: Allows players to use all /permissions subcommands
    children:
      permissions.command: true
      permissions.command.reload: true
      permissions.command.check: true
      permissions.command.info: true
      permissions.command.group: true
      permissions.command.player: true
      permissions.command.help: true
  permissions.command:
    description: Allows players to use the /permissions command
  permissions.command.reload:
    description: Allows players to use the /permissions reload command
  permissions.command.check:
    description: Allows players to use the /permissions check command
  permissions.command.info:
    description: Allows players to use the /permissions info command
  permissions.command.group:
    description: Allows players to use the /permissions group command
  permissions.command.player:
    description: Allows players to use the /permissions player command
  permissions.command.help:
    description: Allows players to use the /permissions help command